apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: {{ .Values.database.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
