apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 8080  # Assuming this is the port your worker container listens on
