apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
      - name: wait-for-control-plane
        image: curlimages/curl:latest
        command:
        - sh
        - -c
        - |
          until curl --silent --fail control-plane:8080/ready;
          do
            echo "waiting for control-plane"
            sleep 2
          done
      containers:
      - name: worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        env:
        - name: POSTGRES_HOST
          value: "{{ .Values.database.host }}"
        - name: POSTGRES_USER
          value: "{{ .Values.database.user }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POSTGRES_DB
          value: "{{ .Values.database.name }}"
